### ISSUE TITLE
Zoom number for each team

### ISSUE THREAD

**Issue by audrism** [fdac20/news#10]
please share you team's zoom number by commenting on this issue

**Comment by alambe22** [comment]
This is team newsBias's zoom link:
https://tennessee.zoom.us/j/91408896943

**Comment by gymmyp1** [comment]
Billboard100: https://tennessee.zoom.us/j/3939099316

**Comment by mdicus** [comment]
Olympics: https://tennessee.zoom.us/j/96713656851

**Comment by tuckermiles70** [comment]
TwitterSentiment: https://tennessee.zoom.us/j/96416981430

**Comment by chupi** [comment]
NetworkIntrustion: https://tennessee.zoom.us/j/95517214080

**Comment by jtbryan** [comment]
AppPermissions: https://tennessee.zoom.us/j/91672070940

**Comment by mwermert** [comment]
Debate Analysis: https://tennessee.zoom.us/j/8671212362

**Comment by davidalanreid** [comment]
SecurityVulnerabilities: https://tennessee.zoom.us/j/96606022135

**Comment by abhidya** [comment]
Emoji Context: https://tennessee.zoom.us/j/7355437957

**Comment by Abhi-Ravi** [comment]
RoadSafety: https://tennessee.zoom.us/j/7887946203

**Comment by dnguye201** [comment]
FoodRec: https://tennessee.zoom.us/j/2365079269

**Comment by spatel38305** [comment]
RateMyProfessors: https://tennessee.zoom.us/j/8145700408

**Comment by mrstark97** [comment]
Presidential Poll: https://tennessee.zoom.us/j/4698520661

**Comment by bhl19950207** [comment]
Digital Currency: https://zoom.us/j/93762046342?pwd=TlA4TVZ0UVVCc3lxVG8vYmNYQW1wZz09 
Passcode: 123

**Comment by kemalfidan** [comment]
https://tennessee.zoom.us/j/92931020017

**Comment by jgurganu** [comment]
BikeShare: https://tennessee.zoom.us/j/97472848970

**Comment by braymar** [comment]
StockPrices: https://zoom.us/j/5985407628?pwd=L3hwTnVzV3NsOERaR3lVY0Y3OXpvUT09

**Comment by Ktailor34** [comment]
Spotify Song: https://tennessee.zoom.us/j/98380578587
