### ISSUE TITLE
Jupyter Notebook Question

### ISSUE THREAD

**Issue by jlangst6** [fdac20/news#12]
I accidentally shut down jupyter notebook on my da2 container and can no longer access it through localhost:8888. I've tried running "jupyter notebook" in the command line, but I get "OSError: [Errno 99] Cannot assign requested address". What command can I run to start jupyter notebook again?

Thanks!

**Comment by jlangst6** [comment]
Just saw issue #5 . "jupyter notebook --no-browser --ip=127.0.0.1 &" fixed it for me.

**Comment by audrism** [comment]
Great!
