### ISSUE TITLE
Trouble Logging into da2

### ISSUE THREAD

**Issue by vickit144** [fdac20/news#13]
Hi @audrism ,

When I ssh into da2, I am unable to log in to it via password (even when I put the correct password for my netid, I get permission denied). I changed environments in where I ssh from and was wondering if you could update my pub id rsa key? 
My netid is wph612 and the new key is 
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDPjhNkOcb6lkRhsHrotj2bCCtTO8FYccTxeMJI0Q13PDJK0bbTe3KjIClMU65wyUlVyI1IBXN+cnhnDkWuJM1HTarrX1mYvGxDtwlVObeCGWK0CYH00bTTgDLfUnCiVUGUD1VMBYbxB0I3GaJhvrHPJizZnooeCHFQ5zZO9M3hZg9tqP4A3VrJ2Xgi7Xb1FLzjn2YUqvhBWmopkYZs10UENcFY3Z/yAKFnwn1H6zT4JcsqNH2A+r4xDh7tDT8rCoBq9N8vfAOUaFiSH0wERzptn4Z7PgzlHRlRUxhSXsYomsQ/A+hJLUmbsqqzb2tThUmRnSFFJ6BZCwWnvOutKUXL VICKI@DESKTOP-J7J2C07

Sorry for the trouble and thank you in advance!

**Comment by audrism** [comment]
Apologies, it seems that authentication client crashed. I restarted it and it should work now

**Comment by vickit144** [comment]
Everything is good now. Thanks for the fix!

**Comment by vickit144** [comment]
Hello Dr. Mockus,

I am currently going through the same issue again with authentication. @audrism

**Comment by audrism** [comment]
Just fixed, sorry about it

**Comment by vickit144** [comment]
Thank you again!

**Comment by vickit144** [comment]
@audrism I tried logging but it says the connection refused. I am trying to connect to port 7957.

**Comment by audrism** [comment]
Looks like sshd died (or may be I cilled it accidentaly). Please try now

**Comment by vickit144** [comment]
Everything is good now! Thank you!
