### ISSUE TITLE
Trouble getting into da2

### ISSUE THREAD

**Issue by tjames17** [fdac20/news#16]
I had da2 running in the background for runB.sh and my computer accidentally restarted in the process and now when I try to ssh  into da2 from windows powershell I get this:

Warning: Permanently added '[da2.eecs.utk.edu]:7926,[160.36.59.121]:7926' (ECDSA) to the list of known hosts.
Connection closed by 160.36.59.121 port 7926

Is there a way to stop it from closing the connection upon login?

**Comment by audrism** [comment]
Should work now) 
Here is a fix to a problem of sssd  occasionally going nuts:
if you login to da2 (port 22) 
```
da2> docker ps -a | grep 7926
993aad3d2fc8        audris/jupyter-r:latest   "/bin/startsvc.sh ..."   2 months ago        Up 2 months             0.0.0.0:7926->22/tcp                                                                     tjames17
da2> docker exec -it tjames17 bash
root@993aad3d2fc8:/home/tjames17# ps -ef
UID        PID  PPID  C STIME TTY          TIME CMD
root         1     0  0 Aug19 ?        00:14:16 /bin/bash /bin/startsvc.sh tjame
root         9     1  0 Aug19 ?        00:00:12 /usr/sbin/sssd -fd 2
....
root@993aad3d2fc8:/home/tjames17# su - tjames17
su: System error
root@993aad3d2fc8:/home/tjames17# kill  9 
root@993aad3d2fc8:/home/tjames17#  /usr/sbin/sssd -fd 2
```

Can you login to da2 directly?

**Comment by tjames17** [comment]
yes thanks!
